name: Laravel CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl
    - name: Install Composer deps
      run: composer install --prefer-dist --no-interaction --no-ansi
    - name: Generate APP_KEY
      run: php artisan key:generate --force
    - name: Run Migrations
      run: php artisan migrate --force
    - name: Run Tests
      run: php artisan test --no-interaction
