name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with PostgreSQL extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # sesuaikan versi PHP
        extensions: pgsql, pdo_pgsql, bcmath, mbstring, tokenizer, xml, curl, sqlite, fileinfo

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Configure database settings for testing
      run: |
        php -r "file_put_contents('.env', str_replace(
          ['DB_HOST=127.0.0.1', 'DB_DATABASE=laravel', 'DB_USERNAME=root', 'DB_PASSWORD='],
          ['DB_HOST=localhost', 'DB_DATABASE=laravel_test', 'DB_USERNAME=postgres', 'DB_PASSWORD=postgres'],
          file_get_contents('.env')
        ));"

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test
